# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath G:/4_modelsim/win64
create_project -in_memory -part xc7z010clg400-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/0_Vivado_prj_learn/Pool_0305/Pool.cache/wt [current_project]
set_property parent.project_path G:/0_Vivado_prj_learn/Pool_0305/Pool.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/0_Vivado_prj_learn/Pool_0305/Pool.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog G:/0_Vivado_prj_learn/Pool_0305/0205NPU/rtl/00_TOP/TOP_hardware_defines.vh
read_verilog -library xil_defaultlib {
  G:/0_Vivado_prj_learn/Pool_0305/0205NPU/rtl/04_POOL/POOL_cal.v
  G:/0_Vivado_prj_learn/Pool_0305/0205NPU/rtl/04_POOL/POOL_rd_SRAM_ctrl.v
  G:/0_Vivado_prj_learn/Pool_0305/0205NPU/rtl/04_POOL/POOL_wr_SRAM_ctrl.v
  G:/0_Vivado_prj_learn/Pool_0305/0205NPU/rtl/00_TOP/sirv_gnrl_dffs.v
  G:/0_Vivado_prj_learn/Pool_0305/0205NPU/rtl/04_POOL/POOL_TOP.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top POOL_TOP -part xc7z010clg400-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef POOL_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file POOL_TOP_utilization_synth.rpt -pb POOL_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
