#!/usr/bin/env python3
"""Generate directed/random POOL_cal stimulus into a SystemVerilog include file.

Usage:
  python scripts/gen_pool_cal_cases.py

Output:
  0205NPU/tb/generated/pool_cal_cases_auto.vh
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import List, Sequence, Union


MAX_DAT_DW = 16
MIN_SIGNED = -(1 << (MAX_DAT_DW - 1))
MAX_SIGNED = (1 << (MAX_DAT_DW - 1)) - 1


# Manual constraints: tune these fields for new regressions.
CONSTRAINTS = {
    "random_seed": 20260305,
    "random_cases": 200,
    "win_len_min": 1,
    "win_len_max": 12,
    "valid_probability": 0.70,
}


@dataclass
class Beat:
    vld: Union[int, str]
    dat: int
    first: int
    last: int


@dataclass
class Case:
    name: str
    beats: Sequence[Beat]
    expected: int


def sv_bit(v: Union[int, str]) -> str:
    if isinstance(v, str):
        return v
    return "1'b1" if int(v) else "1'b0"


def s16_wrap(v: int) -> int:
    v &= 0xFFFF
    if v & 0x8000:
        v -= 0x10000
    return v


def sv_s16(v: int) -> str:
    # Hex form avoids edge-case formatting around -32768.
    return f"16'sh{(v & 0xFFFF):04x}"


def make_directed_cases() -> List[Case]:
    return [
        Case("W0_single_point", [Beat(1, 5, 1, 1)], 5),
        Case("W1_positive", [Beat(1, 3, 1, 0), Beat(1, 12, 0, 0), Beat(1, 7, 0, 1)], 12),
        Case("W2_all_negative", [Beat(1, -8, 1, 0), Beat(1, -3, 0, 0), Beat(1, -20, 0, 1)], -3),
        Case("W3_first_invalid", [Beat(0, 0, 1, 0), Beat(1, -1, 0, 0), Beat(1, 4, 0, 1)], 4),
        Case("W4_all_invalid", [Beat(0, 0, 1, 0), Beat(0, 0, 0, 0), Beat(0, 0, 0, 1)], MIN_SIGNED),
        Case("W5_equal_tie", [Beat(1, 9, 1, 0), Beat(1, 9, 0, 0), Beat(1, 8, 0, 1)], 9),
        Case(
            "W6_mixed_fixed",
            [Beat(1, -100, 1, 0), Beat(1, 45, 0, 0), Beat(1, 23, 0, 0), Beat(1, 102, 0, 0), Beat(1, -7, 0, 1)],
            102,
        ),
        Case("W7_x_vld_ignored", [Beat(1, 2, 1, 0), Beat("1'bx", 30000, 0, 0), Beat(1, 7, 0, 1)], 7),
    ]


def make_random_cases() -> List[Case]:
    rng = random.Random(CONSTRAINTS["random_seed"])
    cases: List[Case] = []

    for cid in range(CONSTRAINTS["random_cases"]):
        win_len = rng.randint(CONSTRAINTS["win_len_min"], CONSTRAINTS["win_len_max"])
        beats: List[Beat] = []
        exp_max = MIN_SIGNED

        for i in range(win_len):
            vld = 1 if rng.random() < CONSTRAINTS["valid_probability"] else 0
            dat = rng.randint(MIN_SIGNED, MAX_SIGNED)
            dat = s16_wrap(dat)
            if vld == 1 and dat > exp_max:
                exp_max = dat
            beats.append(Beat(vld=vld, dat=dat, first=1 if i == 0 else 0, last=1 if i == win_len - 1 else 0))

        cases.append(Case(name=f"RND_{cid}_len{win_len}", beats=beats, expected=exp_max))

    return cases


def emit_case_lines(cases: Sequence[Case]) -> List[str]:
    lines: List[str] = []
    for c in cases:
        lines.append(f"    // {c.name}")
        for b in c.beats:
            lines.append(
                "    drive_beat({vld}, {dat}, {first}, {last});".format(
                    vld=sv_bit(b.vld), dat=sv_s16(b.dat), first=sv_bit(b.first), last=sv_bit(b.last)
                )
            )
        lines.append(f"    check_last(\"{c.name}\", {sv_s16(c.expected)});")
        lines.append("")
    return lines


def build_sv(cases: Sequence[Case]) -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    header = [
        "// Auto-generated by scripts/gen_pool_cal_cases.py",
        f"// Generated at: {now}",
        "// Do not hand-edit this file; update constraints/script and regenerate.",
        "",
        "task automatic run_auto_cases;",
        "begin",
    ]
    body = emit_case_lines(cases)
    tail = [
        "end",
        "endtask",
        "",
    ]
    return "\n".join(header + body + tail)


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    out_file = repo_root / "0205NPU" / "tb" / "generated" / "pool_cal_cases_auto.vh"
    out_file.parent.mkdir(parents=True, exist_ok=True)

    all_cases = make_directed_cases() + make_random_cases()
    out_file.write_text(build_sv(all_cases), encoding="ascii")

    print(f"Generated: {out_file}")
    print(f"Total cases: {len(all_cases)}")


if __name__ == "__main__":
    main()
